version: '3'

services:
  leaderboard-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - API_KEY=${API_KEY}
      - MORALIS_API_KEYS=${MORALIS_API_KEYS}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - LEADERBOARD_SERVER_PORT=3001
    volumes:
      - ./public:/app/public
      - ./assets:/app/assets
    restart: unless-stopped
